version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "1StrongPwd!!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: php_backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - sqlserver
    ports:
      - "8000:80"
    networks:
      - app-network

  vvvebjs:
    image: httpd:2.4
    container_name: vvvebjs_frontend
    volumes:
      - ./vvvebjs:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
