version: '3.9'
services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu_plesk
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
    entrypoint: ["/bin/bash", "-c"]
    stdin_open: true
    tty: true
    restart: always
    networks:
      - localhost-network
    environment:
      - DEBIAN_FRONTEND=noninteractive
    init: true

  plesk:
    image: plesk/plesk
    container_name: plesk_server
    privileged: true
    ports:
      - "8880:8880"  # Expõe a porta corretamente
      - "443:443"    # HTTPS, caso necessário
      - "80:80"      # HTTP, caso necessário
    restart: always
    networks:
      - localhost-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "1StrongPwd!!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - localhost-network

  backend:
    build: ./backend
    container_name: php_backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - sqlserver
    ports:
      - "8000:80"
    networks:
      - localhost-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vvveb
      MYSQL_DATABASE: vvveb
      MYSQL_USER: vvveb
      MYSQL_PASSWORD: vvveb
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - localhost-network

  vvvebjs:
    image: vvveb/vvvebcms:php8.3-fpm-alpine
    environment:
      DB_HOST: db
      DB_DATABASE: vvveb
      DB_USER: vvveb
      DB_PASSWORD: vvveb
      DB_ENGINE: mysqli
    container_name: vvvebjs_frontend
    ports:
      - "8080:80"
    volumes:
      - ./vvveb_data:/var/www/vvveb/
      - db:/var/lib/mysql
    networks:
      - localhost-network

volumes:
  vvveb-volume:
  db:

networks:
  localhost-network:
    driver: bridge
