version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vvveb
      MYSQL_DATABASE: vvveb
      MYSQL_USER: vvveb
      MYSQL_PASSWORD: vvveb
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - localhost-network

  vvvebjs:
    image: vvveb/vvvebcms:php8.3-fpm-alpine
    environment:
      DB_HOST: db
      DB_DATABASE: vvveb
      DB_USER: vvveb
      DB_PASSWORD: vvveb
      DB_ENGINE: mysqli
    container_name: vvvebjs_frontend
    ports:
      - "8080:80"
    volumes:
      - ./vvveb_data:/var/www/vvveb/
      - db:/var/lib/mysql
    networks:
      - localhost-network

volumes:
  db:

networks:
  localhost-network:
    driver: bridge
